import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex m-2">
          <div className="block m-2">
            <Link href={`/posts`} className="text-blue-500 font-medium hover:underline active:underline">Posts list</Link>
          </div>
          <div className="block m-2">
            <Link href={`/`} className="text-blue-500 font-medium hover:underline active:underline">Map</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
